language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
matrix:
  fast_finish: true
sudo: false
env:
- TZ=Etc/UTC
- TZ=America/Los_Angeles
- TZ=Asia/Tokyo
before_install:
- npm install -g grunt-cli
- date
script:
- grunt ci
deploy:
  provider: npm
  email: simon@simonemms.com
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/datautils-js
  api_key:
    secure: B3ukXkRqP8vutagGeype6j1HlGUhYiaJGwsMBhd5D8ywbbCa/0J9eRJdUTm/BQaoENdjjtGDE1P6ex66e1/FSW9i15I/gFBdN6ZTLCshGZevrOMQ0ie5WFsBnSRReD/ZKevbX0w2tvqFsOtPKq0kGqgyRx7TjhGp3sinv23QsDI=
