language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
matrix:
  fast_finish: true
sudo: false
env:
- TZ=Etc/UTC
- TZ=America/Los_Angeles
- TZ=Asia/Tokyo
before_install:
- npm install -g grunt-cli
- date
script:
- grunt ci
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: CpWDYsiWYweRMdlyjU3D90MeHJEZByYPviEedpS62iGMw0MbtpMtpOaN8LDb2Fkd1aQp8hrDY3iIGMvFC/Tlz5nH+tt04e3JRokrvtRS1M9XsGjudHydArHxGWAV1JQkFv7x6tYkh31QwWikHL0kGgC3ZwZCreANoCyt/D5nEbQ=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/datautils-js
