language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.11'
  - node_js: '0.6'
before_install:
- npm conf set strict-ssl false
script:
- ant -f build.xml ci
notifications:
  email:
    recipients:
    - simon@simonemms.com
    on_success: change
    on_failure: always
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: kjApwALU8bY+JX5CHaLKEWIS93Tv+w+7IBU7cTCELGJvdOk9EQKBhVMjhp2AUtHu00fzStQdU8khAt9nUQ/bIsB+cCFIaEsm11hDIwKVU2eu5IHeM5TNtVKoaqQZVhTYEt/jXeX4QIxTORDgPKVsYZBnvWHFT+mxqtZuTdEq5r0=
  on:
    tags: true
    repo: riggerthegeek/datautils-js
